In [1]:
#Numpy

In [2]:
!pip install numpy

In [3]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.3.5


In [6]:
#creating arrays

In [7]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [11]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#Dimensions


In [16]:
0-D in Numpy is called a Scalar.
1-D array in Numpy is called a Vector.
2- D array in Numpy is called a Matrix.
3-D array in Numpy is called a Tensor.

SyntaxError: invalid syntax (2697644269.py, line 1)

In [17]:
#Properties of array

In [18]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
print(arr.ndim)

2


In [20]:
print(arr.shape)


(2, 3)


In [21]:
#Create 3D dimensions.

In [23]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print("Dimensions:", arr.ndim)
print("size:",arr.size)
print("shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Total Dimensions:",arr.ndim)

Dimensions: 3
size: 8
shape: (2, 2, 2)
Data Type: int64
Total Dimensions: 3


In [25]:
#np.zeros()creates an array filled with 0s.

In [26]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [27]:
import numpy as np
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#Indexing & slicing

In [30]:
sample_array = np.array([10,20,30,40])

In [31]:
sample_array

array([10, 20, 30, 40])

In [32]:
sample_array[0]

np.int64(10)

In [33]:
sample_array[2]

np.int64(30)

In [34]:
sample_array[-1]

np.int64(40)

In [35]:
#Slicing

In [36]:
sample_array[1:3]

array([20, 30])

In [37]:
# Array operations

In [38]:
a = np.array([1,2,3])

In [39]:
b = np.array([4,5,6])

In [40]:
a

array([1, 2, 3])

In [41]:
b

array([4, 5, 6])

In [42]:
a + b

array([5, 7, 9])

In [43]:
a - b

array([-3, -3, -3])

In [44]:
a * b

array([ 4, 10, 18])

In [45]:
a / b

array([0.25, 0.4 , 0.5 ])

In [46]:
a = np.array([5,3,1])


In [56]:
b = np.array([8,6,1])

In [49]:
a

array([5, 3, 1])

In [57]:
b

array([8, 6, 1])

In [58]:
a + b

array([13,  9,  2])

In [59]:
a - b

array([-3, -3,  0])

In [60]:
a * b

array([40, 18,  1])

In [61]:
a / b

array([0.625, 0.5  , 1.   ])

In [62]:
# Mathematical Functions.

In [64]:
sample_array = np.array([1,4,9])

In [65]:
sample_array

array([1, 4, 9])

In [66]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [67]:
sample_array = np.array([8,13,5])

In [68]:
sample_array

array([ 8, 13,  5])

In [69]:
np.sqrt(sample_array)

array([2.82842712, 3.60555128, 2.23606798])

In [70]:
np.exp(sample_array)

array([2.98095799e+03, 4.42413392e+05, 1.48413159e+02])

In [71]:
np.log(sample_array)

array([2.07944154, 2.56494936, 1.60943791])

In [72]:
#Statistical Functions

In [73]:
sample_array = np.array([1,2,3,4,5])

In [74]:
sample_array

array([1, 2, 3, 4, 5])

In [75]:
np.mean(sample_array)

np.float64(3.0)

In [76]:
np.median(sample_array)

np.float64(3.0)

In [78]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [79]:
np.min(sample_array)

np.int64(1)

In [80]:
np.max(sample_array)

np.int64(5)

In [81]:
#Reshaping Arrays

In [83]:
sample_array =np.arange(6)

In [84]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [86]:
reshaped = sample_array.reshape(2,3)

In [87]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
#Flattening

In [89]:
sample_array = np.array([[1,2],[3,4]])

In [90]:
sample_array

array([[1, 2],
       [3, 4]])

In [91]:
sample_array.flatten()

array([1, 2, 3, 4])

In [92]:
sample_array = np.array([[2,3],[5,4],[7,6]])

In [93]:
sample_array

array([[2, 3],
       [5, 4],
       [7, 6]])

In [94]:
sample_array.flatten()

array([2, 3, 5, 4, 7, 6])

In [95]:
sample_tensor_3 = np.array([[[1,2],[3,4],[5,6],[8,7]]])

In [96]:
sample_tensor_3.flatten()

array([1, 2, 3, 4, 5, 6, 8, 7])

In [97]:
# Joining Arrays

In [98]:
a = np.array([1,2])


In [99]:
b = np.array([3,4])

In [100]:
a

array([1, 2])

In [101]:
b

array([3, 4])

In [102]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [103]:
# spliting arrays

In [104]:
sample_array = np.array([1,2,3,4])

In [105]:
sample_array

array([1, 2, 3, 4])

In [106]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [107]:
#Random module

In [108]:
np.random.rand(3)

array([0.48036339, 0.16530816, 0.88981138])

In [109]:
np.random.randint(1,10,5)

array([2, 1, 7, 7, 7], dtype=int32)

In [111]:
#Axis concept

In [112]:
sample_array = np.array([[1,2],[3,4]])

In [113]:
sample_array

array([[1, 2],
       [3, 4]])

In [114]:
np.sum(sample_array, axis=0)

array([4, 6])

In [115]:
np.sum(sample_array,axis=1)

array([3, 7])

In [116]:
# NaN & Missing values

In [117]:
sample_array = np.array([1,np.nan,3])

In [118]:
sample_array

array([ 1., nan,  3.])

In [119]:
np.isnan(sample_array)

array([False,  True, False])

In [128]:
# create 2 numpy arrays & perform element wise addition,subtraction,multiplication and modulus operation

In [130]:
arr1 = np.array([5, 10, 15, 20])
arr2 = np.array([2, 3, 4, 5])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
modulus = arr1 % arr2

print("Array 1:",arr1)
print("array 2:",arr2)

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Modulus:", modulus)

Array 1: [ 5 10 15 20]
array 2: [2 3 4 5]
Addition: [ 7 13 19 25]
Subtraction: [ 3  7 11 15]
Multiplication: [ 10  30  60 100]
Modulus: [1 1 3 0]
